"""Add auth_provider column

Revision ID: 2db9759a7588
Revises: b2871f814127
Create Date: 2026-07-10 16:36:58.524501

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db9759a7588'
down_revision: Union[str, Sequence[str], None] = 'b2871f814127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('auth_provider', sqlmodel.sql.sqltypes.AutoString(), server_default='local', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###
