"""Create Document Table

Revision ID: a3ed706c4846
Revises: 9e67cbc2dd0a
Create Date: 2026-07-23 15:04:56.617762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql

# revision identifiers, used by Alembic.
revision: str = 'a3ed706c4846'
down_revision: Union[str, Sequence[str], None] = '9e67cbc2dd0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Truncate any old test rows if table exists with old schema
    op.execute("TRUNCATE TABLE documents CASCADE;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('documents', sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), server_default='', nullable=False))
    op.add_column('documents', sa.Column('file_size_bytes', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('documents', 'filename',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('documents', 'storage_path',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    
    # Create new enum type in Postgres if it does not exist yet
    filestatus_enum = sa.Enum('UPLOADED', 'PROCESSING', 'INDEXED', 'FAILED', name='filestatus')
    filestatus_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column('documents', 'status',
               existing_type=postgresql.ENUM('UPLOADED', 'PROCESSING', 'READY', 'FAILED', 'DELETING', name='documentstatus'),
               type_=filestatus_enum,
               postgresql_using='status::text::filestatus',
               existing_nullable=False)
    op.alter_column('documents', 'chat_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('documents_storage_path_key'), 'documents', type_='unique')
    op.create_index(op.f('ix_documents_filename'), 'documents', ['filename'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)

    op.create_foreign_key(None, 'documents', 'chats', ['chat_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'])
    op.drop_column('documents', 'storage_bucket')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'chunk_count')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'processed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('chunk_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('mime_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('storage_bucket', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_filename'), table_name='documents')
    op.create_unique_constraint(op.f('documents_storage_path_key'), 'documents', ['storage_path'], postgresql_nulls_not_distinct=False)
    op.alter_column('documents', 'chat_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('documents', 'status',
               existing_type=sa.Enum('UPLOADED', 'PROCESSING', 'INDEXED', 'FAILED', name='filestatus'),
               type_=postgresql.ENUM('UPLOADED', 'PROCESSING', 'READY', 'FAILED', 'DELETING', name='documentstatus'),
               existing_nullable=False)
    op.alter_column('documents', 'storage_path',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('documents', 'filename',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('documents', 'file_size_bytes')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'updated_at')
    # ### end Alembic commands ###
